options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Google Cloud Logging

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']

images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'
