options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Google Cloud Logging

substitutions:
  _IMAGE_NAME: "gcpdevops-dev"  # Define image name as a variable

steps:
  # Step 1: Build Docker image with SHA-based tagging for rollback support
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA', '.']

  # Step 2: Push Docker image to Google Artifact Registry (or GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA']

  # Step 3: Deploy to GKE with dynamically updated image reference
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/$_IMAGE_NAME:$SHORT_SHA  # Use SHA-tagged image
      - --location=us-central1-c  
      - --cluster=gcp-devops-project  
      - --namespace=gcp-devops-dev  
      - --filename=gke.yaml