steps:
  - name: 'gcr.io/cloud-builders/docker'  # Use the correct builder image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

  - name: 'gcr.io/cloud-builders/docker'  # Push the image after building
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']

images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'
