options:
  logging: CLOUD_LOGGING_ONLY  # Send logs to Google Cloud Logging

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops-dev', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops-dev']

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --image=gcr.io/$PROJECT_ID/gcpdevops-dev
      - --location=us-central1-c  
      - --cluster=gcp-devops-project  # Correct cluster name
      - --namespace=gcp-devops-dev  # Keep the specified namespace
      - --filename=gke.yaml
